version: "3.9"
services:
  db:
    image: postgres:16
    container_name: meds_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medicines
    ports: ["55432:5432"]              
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d medicines"]  
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: meds_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/medicines
    ports: ["8000:8000"]
    restart: unless-stopped

volumes:
  dbdata:
